package models;
// Generated 05-mar-2021 17:56:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Personajes generated by hbm2java
 */
public class Personajes  implements java.io.Serializable {


     private BigDecimal idpersonaje;
     private String personaje;
     private String imagen;
     private BigDecimal idserie;

    public Personajes() {
    }

	
    public Personajes(BigDecimal idpersonaje) {
        this.idpersonaje = idpersonaje;
    }
    public Personajes(BigDecimal idpersonaje, String personaje, String imagen, BigDecimal idserie) {
       this.idpersonaje = idpersonaje;
       this.personaje = personaje;
       this.imagen = imagen;
       this.idserie = idserie;
    }
   
    public BigDecimal getIdpersonaje() {
        return this.idpersonaje;
    }
    
    public void setIdpersonaje(BigDecimal idpersonaje) {
        this.idpersonaje = idpersonaje;
    }
    public String getPersonaje() {
        return this.personaje;
    }
    
    public void setPersonaje(String personaje) {
        this.personaje = personaje;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public BigDecimal getIdserie() {
        return this.idserie;
    }
    
    public void setIdserie(BigDecimal idserie) {
        this.idserie = idserie;
    }




}


